# Generated by Django 5.2 on 2025-04-30 13:59

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='disliked_tracks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='liked_tracks',
        ),
        migrations.AlterField(
            model_name='user',
            name='disliked_artists',
            field=models.JSONField(default=list, help_text='Enter artists as JSON array', validators=[users.models.User.validate_json]),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_artists',
            field=models.JSONField(default=list, help_text='Enter artists as JSON array', validators=[users.models.User.validate_json]),
        ),
    ]
