# Generated by Django 5.2 on 2025-05-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('audio_file', models.FileField(upload_to='music/audio/')),
                ('artwork', models.ImageField(blank=True, null=True, upload_to='music/artwork/')),
                ('emotions', models.ManyToManyField(blank=True, related_name='tracks', to='music.emotion')),
            ],
            options={
                'db_table': 'music_track',
            },
        ),
    ]
