# Generated by Django 5.2 on 2025-05-05 19:13


from django.db import migrations, models 
from django.conf import settings
def fill_thumbnail_url(apps, schema_editor):
    Track = apps.get_model('music', 'Track')
    for track in Track.objects.all():
        track.thumbnail_url = "https://i.ytimg.com/vi/default/maxresdefault.jpg"
        track.save()
class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='thumbnail_url',
            field=models.URLField(max_length=500, blank=True, null=True),
        ),
        migrations.RunPython(fill_thumbnail_url),
        migrations.AlterField(
            model_name='track',
            name='thumbnail_url',
            field=models.URLField(max_length=500),
        )
    ]